Repository open-rpc/typings, pull requests merged in 2019-05, with the labels that each got.

#1 fix: names
  .circleci/config.yml
  package.json
Labels: bug

#10 fix(README): example usage of constructor
  README.md
Labels: bug

#16 fix: handle typename uniqueness naively
  package-lock.json
  package.json
  src/index.test.ts
  src/index.ts
  src/rust.ts
  src/typescript.ts
Labels: bug

#18 fix: build doesnt have a src dir
  package.json
Labels: bug

#19 fix: typedoc stuff
  tsconfig.json
Labels: bug

#20 fix: unique typenames
  src/index.test.ts
  src/rust.ts
Labels: bug

#21 fix: dedupe by equal schemas
  src/index.test.ts
  src/rust.ts
Labels: bug

#24 fix: wrangle the beast into submission
  src/rust.ts
Labels: bug

#36 feat: add type alias function
  src/generator-interface.ts
  src/index.test.ts
  src/index.ts
  src/rust.ts
  src/typescript.ts
Labels: enhancement

#41 fix: typescript function alias incorrect
  src/index.test.ts
  src/typescript.ts
Labels: bug

#43 fix: typescript needs unique typenames
  src/index.test.ts
  src/typescript.ts
Labels: bug

#45 fix: enums are made as interfaces
  src/typescript.ts
Labels: bug

#46 fix: support oneOf
  src/typescript.ts
Labels: bug

#47 feat: use atomic naming of schemas
  package-lock.json
  src/generator-interface.ts
  src/index.test.ts
  src/index.ts
  src/rust.ts
  src/typescript.ts
  tslint.json
Labels: bug, enhancement

#49 fix: items can be an array or an object
  package-lock.json
  src/index.test.ts
  src/index.ts
  src/rust.ts
  src/typescript.ts
Labels: bug
